version: "2.1"
volumes:
  dml_app:
    driver_opts:
      type: "nfs"
      o: "addr=222.201.187.50,ro"
      device: ":/home/qianguo/controller/dml_app"
  dataset:
    driver_opts:
      type: "nfs"
      o: "addr=222.201.187.50,ro"
      device: ":/home/qianguo/controller/dataset"
services:
  n7:
    container_name: n7
    image: dml:v1.0
    working_dir: /home/qianguo/worker/dml_app
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    cpuset: 90-95
    mem_limit: 2048M
    environment:
      - EDGE_TB_ID=7
      - NET_NODE_NAME=n7
      - DML_PORT=4444
      - NET_CTL_ADDRESS=222.201.187.50:3333
      - NET_AGENT_ADDRESS=222.201.187.51:3333
    healthcheck:
      test: curl -f http://localhost:4444/hi
    ports:
      - "8007:4444"
    volumes:
      - ./dml_file:/home/qianguo/worker/dml_file
      - dml_app:/home/qianguo/worker/dml_app/:ro
      - dataset:/home/qianguo/worker/dataset/:ro
    command: python3 gl_peer.py